
services:
  consul:
    image: hashicorp/consul:1.21.5
    container_name: consul
    ports:
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: >
      consul agent
        -server
        -bootstrap
        -ui
        -client=0.0.0.0
        -data-dir=/consul/data
    volumes:
      - consul_data:/consul/data
    networks:
      - eth_validator_network
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 3s
      retries: 3

  vault:
    image: hashicorp/vault:1.20.4
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=dev-root-token
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data
      - ./vault/config:/vault/config
      - ./vault/init:/vault/init
    networks:
      - eth_validator_network
    # depends_on:
    #   consul:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 3s
      retries: 3
    command: >
      sh -c "
        vault server -config=/vault/config/vault.hcl &
        sleep 10 &&
        export VAULT_ADDR=http://localhost:8200 &&
        vault auth -method=userpass username=admin password=admin ||
        (
          vault auth -method=token token=dev-root-token &&
          vault auth enable userpass &&
          vault write auth/userpass/users/admin password=admin policies=admin &&
          vault policy write admin /vault/init/admin-policy.hcl &&
          vault secrets enable -path=secret kv-v2
        ) &&
        wait
      "

  web3signer:
    image: consensys/web3signer:25.9.1
    container_name: web3signer
    ports:
      - "9000:9000"
    volumes:
      - ./web3signer/config:/config
      - ./web3signer/keys:/keys
    networks:
      - eth_validator_network
    depends_on:
      vault:
        condition: service_healthy
    command: >
      --config-file=/config/config.yaml
      --http-listen-host=0.0.0.0
      --http-listen-port=9000
      --key-manager-api-enabled=true
      --metrics-enabled=true
      --metrics-host=0.0.0.0
      --metrics-port=9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/upcheck"]
      interval: 15s
      timeout: 3s
      retries: 3

volumes:
  consul_data:
  vault_data:

networks:
  eth_validator_network:
    driver: bridge