# Web3Signer 25.9.1 Configuration
# This configuration file is compatible with Web3Signer v25.9.1

# Key store configuration for HashiCorp Vault
key-stores:
  - type: "hashicorp-vault"
    vault-url: "http://vault:8200"
    vault-auth-method: "userpass"
    vault-username: "admin"
    vault-password: "admin"
    vault-secrets-path: "secret"
    vault-secrets-engine-version: 2

# Logging configuration
logging:
  level: "INFO"
  format: "JSON"