# Kurtosis Ethereum Package Configuration (Linux-ready)
# Goal: fast validator lifecycle (activate/exit) + external Web3Signer testing

participants:
  - el_type: geth
    el_image: ethereum/client-go:v1.16.3
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v7.1.0
    vc_type: lighthouse
    vc_image: sigp/lighthouse:v7.1.0
    vc_extra_params:
      [
        "--validators-external-signer=http://172.17.0.1:9000",
        "--suggested-fee-recipient=0x0000000000000000000000000000000000000001"
      ]
    el_extra_params: ["--http.api=eth,net,web3,debug,admin,txpool"]

  - el_type: geth
    el_image: ethereum/client-go:v1.16.3
    cl_type: teku
    cl_image: consensys/teku:25.9.3
    vc_type: teku
    vc_image: consensys/teku:25.9.3
    vc_extra_params:
      [
        "--validators-external-signer-url=http://172.17.0.1:9000",
        "--validators-external-signer-public-keys=http://172.17.0.1:9000/api/v1/eth2/publicKeys",
        "--validators-external-signer-slashing-protection-enabled=true",
        "--validators-proposer-default-fee-recipient=0x0000000000000000000000000000000000000001"
      ]
    el_extra_params: ["--http.api=eth,net,web3,debug,admin,txpool"]

network_params:
  preset: minimal
  seconds_per_slot: 4
  genesis_delay: 30

  capella_fork_epoch: 0
  deneb_fork_epoch: 0
  electra_fork_epoch: 0

  num_validator_keys_per_node: 64
  ejection_balance: 16000000000

  network_id: "3151908"
  deposit_contract_address: "0x4242424242424242424242424242424242424242"

additional_services:
  - prometheus
  - grafana
  - forkmon
  - broadcaster     # ← 替代 tx_spammer 的合法流量/交易服务
  - dora

wait_for_finalization: false
global_log_level: info
mev_type: null
