# Kurtosis Ethereum Package Configuration
# This configuration spins up a fast devnet with built-in validators
# External Web3Signer will be used for additional validator management

participants:
  # --- Combo 1: Geth × Lighthouse (Built-in validators) ---
  - el_type: geth
    el_image: ethereum/client-go:v1.16.3
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v7.1.0
    vc_type: lighthouse
    vc_image: sigp/lighthouse:v7.1.0
    el_extra_params: ["--http.api=eth,net,web3,debug,admin,txpool"]

  # --- Combo 2: Geth × Teku (Built-in validators) ---
  - el_type: geth
    el_image: ethereum/client-go:v1.16.3
    cl_type: teku
    cl_image: consensys/teku:25.9.3
    vc_type: teku
    vc_image: consensys/teku:25.9.3
    el_extra_params: ["--http.api=eth,net,web3,debug,admin,txpool"]

network_params:
  # ===== 时间尺度（缩短等待但不跳过）=====
  # slot 缩短，epoch = 32 × 4s = 128s；把 64-epoch 投票期压到 ~2 分钟量级
  seconds_per_slot: 4
  # 缩短 ETH1 跟随距离（主网是 2048）；设 16（甚至 1 也行）
  eth1_follow_distance: 16

  # ===== 激活队列（更快清队列）=====
  # 主网等价：65536；这里降到 32，让每个 epoch 激活更多
  churn_limit_quotient: 32
  max_per_epoch_activation_churn_limit: 64

  # ===== 创世与验证者基数 =====
  # 每台 VC 需要足够的 genesis 验证者以满足最小要求（64个）
  # 2 个节点 × 32 个验证者/节点 = 64 个验证者
  num_validator_keys_per_node: 32
  # 便于提款观察：直接用 0x01，退出后自动提款到 EL 地址
  withdrawal_type: "0x01"

  # ===== 网络配置 =====
  # 使用 minimal preset 以加快共识
  preset: minimal
  # 网络 ID
  network_id: "3151908"
  # 存款合约地址
  deposit_contract_address: "0x4242424242424242424242424242424242424242"
  
  # ===== Fork 配置 =====
  # 启用所有 fork 从 genesis 开始
  capella_fork_epoch: 0
  deneb_fork_epoch: 0
  electra_fork_epoch: 256

  # 预置资金账户（用来批量发送 deposit 交易）
  prefunded_accounts: '{
    "0xDeaDbeefDeaDbeefDeaDbeefDeaDbeefDeaDBeEF": {"balance":"10000ETH"}
  }'

  # 给 EL 启动更宽窗口（避免 CL 先跑起来）
  genesis_delay: 90

# 监控与工具（均为包支持的合法服务名）
additional_services:
  - prometheus_grafana
  - forkmon
  - dora
  - blockscout         # 看 EL 交易/合约
  - tx_fuzz            # 产生交易负载；也可换 broadcaster/custom_flood/spamoor
  - blobscan           # 如需观察 4844 blob

wait_for_finalization: false
global_log_level: info
mev_type: null
