# Kurtosis Ethereum Package Configuration
# This configuration spins up a fast devnet for validator lifecycle testing

participants:
  - el_type: geth
    el_image: ethereum/client-go:v1.16.3
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v7.1.0
    vc_type: lighthouse
    vc_image: sigp/lighthouse:v7.1.0
    vc_extra_params: ["--enable-web3signer-slashing-protection", "--web3-signer-url=http://host.docker.internal:9000"]
    el_extra_params: ["--http.api=eth,net,web3,debug,admin,txpool"]

  - el_type: geth
    el_image: ethereum/client-go:v1.16.3
    cl_type: teku
    cl_image: consensys/teku:25.9.3
    vc_type: teku
    vc_image: consensys/teku:25.9.3
    vc_extra_params: ["--validators-external-signer-public-keys=http://host.docker.internal:9000/api/v1/eth2/publicKeys", "--validators-external-signer-url=http://host.docker.internal:9000"]
    el_extra_params: ["--http.api=eth,net,web3,debug,admin,txpool"]

network_params:
  seconds_per_slot: 12
  genesis_delay: 120
  capella_fork_epoch: 0
  deneb_fork_epoch: 0
  electra_fork_epoch: 0

  # Validator configuration
  num_validator_keys_per_node: 64
  churn_limit_quotient: 32
  ejection_balance: 16000000000

  # Use minimal preset for faster consensus
  preset: minimal

  # Network ID
  network_id: "3151908"
  deposit_contract_address: "0x4242424242424242424242424242424242424242"
  
  # Additional parameters for newer clients
  max_per_epoch_activation_churn_limit: 8
  min_validator_withdrawability_delay: 256
  shard_committee_period: 256
  
  # Fix for newer clients - use proper values
  data_column_sidecar_subnet_count: 1
  samples_per_slot: 1
  custody_requirement: 0
  max_blobs_per_block_electra: 6
  target_blobs_per_block_electra: 3
  max_request_blob_sidecars_electra: 768
  base_fee_update_fraction_electra: 64

# Additional services for monitoring and testing
additional_services:
  - forkmon

# Don't wait for finalization to speed up testing
wait_for_finalization: false

# Global settings
global_log_level: info

# MEV configuration (disabled for simplicity)
mev_type: null