# Kurtosis Ethereum Package Configuration
# Goal: fast devnet with built-in validators; later you can add external Web3Signer

participants:
  # --- Combo 1: Geth × Prysm ---
  - el_type: geth
    cl_type: prysm
    vc_type: prysm

  # --- Combo 2: Reth × Lighthouse ---
  - el_type: reth
    cl_type: lighthouse
    vc_type: lighthouse

  # --- Combo 3: Geth × Lighthouse ---
  - el_type: geth
    cl_type: lighthouse
    vc_type: lighthouse

  # --- Combo 4: Reth × Prysm ---
  - el_type: reth
    cl_type: prysm
    vc_type: prysm

# ⬆️ 不固定镜像：省略 el_image/cl_image/vc_image，让包使用其测试过的默认镜像组合
# ⬆️ 不加 el_extra_params：避免把 geth 专属参数误用到 reth

network_params:
  # ===== 时间尺度（缩短等待但不跳过）=====
  seconds_per_slot: 4
  eth1_follow_distance: 16

  # ===== 激活队列（更快清队列）=====
  churn_limit_quotient: 32
  max_per_epoch_activation_churn_limit: 64

  # ===== 创世与验证者基数 =====
  num_validator_keys_per_node: 32         # 4 组 × 32 = 128 个 genesis 验证者
  withdrawal_type: "0x01"                 # 退出后自动提款到 EL 地址

  # ===== 预设与网络标识 =====
  preset: minimal
  network_id: "3151908"
  deposit_contract_address: "0x4242424242424242424242424242424242424242"

  # ===== Fork 配置（只到 Deneb；先不启 Electra）=====
  altair_fork_epoch: 0
  bellatrix_fork_epoch: 0
  capella_fork_epoch: 0
  deneb_fork_epoch: 0
  # electra_fork_epoch:   # ← 不配置，等网络稳定后再按需开启（建议 256/512）

  # ===== 资金准备（用于后续批量 deposit 测试）=====
  prefunded_accounts: '{
    "0xDeaDbeefDeaDbeefDeaDbeefDeaDbeefDeaDBeEF": {"balance":"10000ETH"}
  }'

  # 给 EL 充足时间就绪，避免 CL 先行导致初始化失败
  genesis_delay: 180

additional_services:
  - prometheus_grafana
  - forkmon
  - dora
  - blockscout
  - tx_fuzz
  - blobscan

wait_for_finalization: false
global_log_level: info
mev_type: null
