"""add_batch_deposit_contracts_table

Revision ID: 742b2ef76cff
Revises: 001
Create Date: 2025-12-03 21:30:00.207947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742b2ef76cff'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_deposit_contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_address', sa.String(length=42), nullable=False),
    sa.Column('network_name', sa.String(length=64), nullable=False),
    sa.Column('rpc_url', sa.String(length=256), nullable=False),
    sa.Column('deployer_address', sa.String(length=42), nullable=False),
    sa.Column('deployment_tx_hash', sa.String(length=66), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('gas_used', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_address'),
    sa.UniqueConstraint('deployment_tx_hash')
    )
    op.create_index(op.f('ix_batch_deposit_contracts_contract_address'), 'batch_deposit_contracts', ['contract_address'], unique=False)
    op.create_index(op.f('ix_batch_deposit_contracts_deployment_tx_hash'), 'batch_deposit_contracts', ['deployment_tx_hash'], unique=False)
    op.create_index(op.f('ix_batch_deposit_contracts_deployed_at'), 'batch_deposit_contracts', ['deployed_at'], unique=False)
    op.create_index(op.f('ix_batch_deposit_contracts_network_name'), 'batch_deposit_contracts', ['network_name'], unique=False)
    op.create_index('idx_network_contract', 'batch_deposit_contracts', ['network_name', 'contract_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_network_contract', table_name='batch_deposit_contracts')
    op.drop_index(op.f('ix_batch_deposit_contracts_network_name'), table_name='batch_deposit_contracts')
    op.drop_index(op.f('ix_batch_deposit_contracts_deployed_at'), table_name='batch_deposit_contracts')
    op.drop_index(op.f('ix_batch_deposit_contracts_deployment_tx_hash'), table_name='batch_deposit_contracts')
    op.drop_index(op.f('ix_batch_deposit_contracts_contract_address'), table_name='batch_deposit_contracts')
    op.drop_table('batch_deposit_contracts')
    # ### end Alembic commands ###

