# Kurtosis Ethereum Package Configuration
# Goal: fast devnet with built-in validators; later you can add external Web3Signer

participants:
  # 1) Geth × Prysm —— 作为归档 + 调试/追踪节点（便于接 Blockscout）
  - el_type: geth
    cl_type: prysm
    vc_type: prysm
    el_extra_params:
      - "--http.api=admin,engine,net,eth,web3,debug,txpool"

  # 2) Reth × Lighthouse —— 常规
  - el_type: reth
    cl_type: lighthouse
    vc_type: lighthouse
    # 不加 geth 专参

  # # 3) Geth × Lighthouse —— 常规 HTTP API
  # - el_type: geth
  #   cl_type: lighthouse
  #   vc_type: lighthouse
  #   el_extra_params:
  #     - "--http.api=admin,engine,net,eth,web3,debug,txpool"

  # # 4) Reth × Prysm —— 常规
  # - el_type: reth
  #   cl_type: prysm
  #   vc_type: prysm

# ⬆️ 不固定镜像：省略 el_image/cl_image/vc_image，让包使用其测试过的默认镜像组合
# ⬆️ 不加 el_extra_params：避免把 geth 专属参数误用到 reth

network_params:
  # ===== 时间尺度（缩短等待但不跳过）=====
  seconds_per_slot: 4
  eth1_follow_distance: 16

  # ===== 激活队列（更快清队列）=====
  churn_limit_quotient: 32
  max_per_epoch_activation_churn_limit: 64

  # ===== 创世与验证者基数 =====
  num_validator_keys_per_node: 64
  withdrawal_type: "0x01"

  # ===== 预设与网络标识 =====
  preset: mainnet
  network_id: "3151908"
  deposit_contract_address: "0x4242424242424242424242424242424242424242"

  # ===== Fork 配置 =====
  altair_fork_epoch: 0
  bellatrix_fork_epoch: 0
  capella_fork_epoch: 0
  deneb_fork_epoch: 0
  electra_fork_epoch: 0

  # ===== 资金准备（用于后续批量 deposit 测试）=====
  prefunded_accounts: '{
    "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266": {"balance":"10000ETH"}
  }'

  # 给 EL 充足时间就绪，避免 CL 先行导致初始化失败
  genesis_delay: 60


wait_for_finalization: false
global_log_level: info
mev_type: null

additional_services:
  - prometheus_grafana
  - forkmon
  - dora